# Generated by Django 3.0.7 on 2020-08-01 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 10, 27, 25, 258479), verbose_name='date published'),
        ),
    ]
