# Generated by Django 3.0.7 on 2020-08-01 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200801_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 19, 23, 58, 478490), verbose_name='date published'),
        ),
    ]
